name: PyPi Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  release:
    types:
      - created

# based on https://github.com/pypa/gh-action-pypi-publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Checking out code from GitHub
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: generate version file
      run: |
        echo "__version__ = '$RELEASE_TAG'" > python_rako/__version__.py
      env:
        RELEASE_TAG: ${{ github.event.ref }}
    - name: Install dependencies
      run: |
        python -m pip install --user --upgrade pip setuptools wheel
    - name: Build
      run: >-
        python setup.py sdist bdist_wheel
    # We do this, since failures on test.pypi aren't that bad
    - name: Publish to Test PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

#    - name: Publish distribution 📦 to PyPI
#      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_TOKEN }}
